export const CHARACTER_CLASSES = [
  'Gladiator',
  'Warlord',
  'Paladin',
  'Dark Avenger',
  'Hawkeye',
  'Treasure Hunter',
  'Sorcerer',
  'Necromancer',
  'Warlock',
  'Bishop',
  'Prophet',
  'Temple Knight',
  'Sword Singer',
  'Plains Walker',
  'Silver Ranger',
  'Spell Singer',
  'Elemental Summoner',
  'Elven Elder',
  'Shillien Knight',
  'Blade Dancer',
  'Abyss Walker',
  'Phantom Ranger',
  'Spellhowler',
  'Phantom Summoner',
  'Shillien Elder',
  'Destroyer',
  'Tyrant',
  'Overlord',
  'Warcryer',
  'Bounty Hunter',
  'Warsmith',
] as const;

export type CharacterClass = (typeof CHARACTER_CLASSES)[number];
