#!/usr/bin/env sh

message="$(cat $1)"
requiredPattern="^(feat|fix|refactor|chore|docs|style|perf|test|ci|build|revert)(\(.*\))?: .*$"
if ! [[ $message =~ $requiredPattern ]];
then
  echo "-"
  echo "🚨 Wrong commit message! 😕"
  echo "The commit message must have this format:"
  echo "<type> <subject>"
  echo "Allowed types: feat, fix, refactor, chore, docs, style, perf, test, ci, build, revert"
  echo "Example: feat: add login button"
  echo "-"
  echo "Your commit message was:"
  echo $message
  echo "-"
  exit 1
fi